### ISSUE TITLE
RFC: initial investigation

### ISSUE THREAD

**Issue by eamonnmag** [inspirehep/invenio-trends#1]
This tool will work across any installation using the elasticsearch endpoint to analyse the trends in the documents, e.g. keyword usage, n-grams, etc. 

This will be based solely on whatever is inside the elastic search document for now. Full text would require access to the whole document which is not something we can control across all installations of invenio.
- [x] Read up on trend analysis techniques.
- [x] Review existing tools, e.g. Google trends.
- [x] Devise an initial prototype mockup
- [x] Devise an initial infrastructure for the analysis

**Comment by kaplun** [comment]
Since this project has the potential to interest other teams, for documentation purposes, @eamonnmag can you give a bit more info (pointers) on what exactly do you have in mind with trends, maybe a sketch of the idea?
